apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: bgp-peer-frr
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - exportPodCIDR: true
      localASN: 65013
      neighbors:
        - peerASN: 65011
          peerAddress: 172.20.0.5/32
          eBGPMultihopTTL: 2
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
      serviceSelector:
        matchLabels:
          app: nginx
