apiVersion: cilium.io/v2alpha1
kind: CiliumBGPPeeringPolicy
metadata:
  name: demo
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - exportPodCIDR: true
      localASN: 65013
      neighbors:
        - peerASN: 65012
          peerAddress: 172.13.37.5/32 # eth0 IP of Bird router
      serviceSelector:
        matchLabels:
          app: productpage
